title: Jiaxuan Zhang's Homepage
page-top-title: Jiaxuan Zhang
# top-section-bg-text: Ocean Engineering
home-subtitle: Jiaxuan Zhang&ensp;|&ensp;张家璇
copyright-text: '&copy; Jiaxuan Zhang 2024. All Rights Reserved.'
